mybatis:
  mapper-locations: classpath*:/mappers/**/*.xml
  type-aliases-package: com.gamgyule.springbootvue.dto
server:
  error:
    include-exception: true
    include-stacktrace: always
  port: 9989
spring:
  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/
  mvc:
    static-path-pattern: /static/**
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: wkddnwls1!
    url: jdbc:mariadb://localhost:3306/spbootvue?useUnicode=true&characterEncoding=utf8
    username: gamgyule
  servlet:
    multipart:
      max-file-size: 5120MB
      max-request-size: 5120MB
      
