mybatis:
  mapper-locations: classpath*:/mappers/**/*.xml
  type-aliases-package: com.gamgyule.springbootvue.dto
server:
  error:
    include-exception: true
    include-stacktrace: always
  port: 9989
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: wkddnwls1!
    url: jdbc:mariadb://localhost:3306/spbootvue?useUnicode=true&characterEncoding=utf8
    username: gamgyule
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
